### PR TITLE
Fix leading spacing on property and function declaration expansion

### PR DESCRIPTION
**Pull request by dafurman**
**Context**
Indentation and spacing was a little off in some Macro expansion, so I wanted to make it more readable.

Given the example protocol:
```swift
@Spyable
public protocol ServiceProtocol {
    var name: String {
        get
    }
    var secondName: String? {
        get
    }

    func initialize(name: String, secondName: String?)
}
```

This is the expansion in `main`:
```swift
class ServiceProtocolSpy: ServiceProtocol {
    var name: String {
        get {
            underlyingName
        }
        set {
            underlyingName = newValue
        }
    }
    var underlyingName: (String )! ⬅️❌
        var secondName: String? ⬅️❌
    var initializeNameSecondNameCallsCount = 0
    var initializeNameSecondNameCalled: Bool {
        return initializeNameSecondNameCallsCount > 0
    }
    var initializeNameSecondNameReceivedArguments: (name: String, secondName: String?)?
    var initializeNameSecondNameReceivedInvocations: [(name: String, secondName: String?)] = []
    var initializeNameSecondNameClosure: ((String, String?) -> Void)?

        func initialize(name: String, secondName: String?) { ⬅️❌
        initializeNameSecondNameCallsCount += 1
        initializeNameSecondNameReceivedArguments = (name, secondName)
        initializeNameSecondNameReceivedInvocations.append((name, secondName))
        initializeNameSecondNameClosure?(name, secondName)
    }
}
```
And this is the expansion in this PR:
```swift
class ServiceProtocolSpy: ServiceProtocol {
    var name: String {
        get {
            underlyingName
        }
        set {
            underlyingName = newValue
        }
    }
    var underlyingName: (String)! ⬅️✅
    var secondName: String? ⬅️✅
    var initializeNameSecondNameCallsCount = 0
    var initializeNameSecondNameCalled: Bool {
        return initializeNameSecondNameCallsCount > 0
    }
    var initializeNameSecondNameReceivedArguments: (name: String, secondName: String?)?
    var initializeNameSecondNameReceivedInvocations: [(name: String, secondName: String?)] = []
    var initializeNameSecondNameClosure: ((String, String?) -> Void)?

    func initialize(name: String, secondName: String?) { ⬅️✅
        initializeNameSecondNameCallsCount += 1
        initializeNameSecondNameReceivedArguments = (name, secondName)
        initializeNameSecondNameReceivedInvocations.append((name, secondName))
        initializeNameSecondNameClosure?(name, secondName)
    }
}
```

**Testing**
Existing tests pass, and the adjusted tests pass.
Screenshot 2023-10-28 at 2 02 57 PM

### CODE REVIEW

**Comment by Matejkob** [comment]
Hello @dafurman, thank you once again for your valuable contribution! I'm currently refactoring the factories in our project to enhance the capabilities of `SwiftSyntaxBuilder`. I have some concerns about merging your changes prior to this refactor. Would it be alright if we hold off on merging for a bit?

**Comment by dafurman** [comment]
> Hello @dafurman, thank you once again for your valuable contribution! I'm currently refactoring the factories in our project to enhance the capabilities of `SwiftSyntaxBuilder`. I have some concerns about merging your changes prior to this refactor. Would it be alright if we hold off on merging for a bit?

Yeah absolutely! No rush on this at all! I don't mind handling the git conflicts and reworking this if necessary after your refactor.

**Comment by Matejkob** [comment]
I've modified several files and simplified the implementation of some nodes, which has resulted in a few conflicts in this PR. Will you find time to resolve them? If not, I can attempt to address them in my free time.

**Comment by dafurman** [comment]
> Will you find time to resolve them? If not, I can attempt to address them in my free time.

Sure! I can probably get to that later today or this weekend!

**Comment by dafurman** [comment]
@Matejkob The PR should be good to go for review now!

**Review by Matejkob — APPROVED** [review]
That is a great improvement! I was quite annoyed about these leading spaces... Great work! Thanks for doin' it! 🫶

**Pull request merged**
